/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TruhlarAmbulanceWeList {
    }
}
declare global {
    interface HTMLTruhlarAmbulanceWeListElement extends Components.TruhlarAmbulanceWeList, HTMLStencilElement {
    }
    var HTMLTruhlarAmbulanceWeListElement: {
        prototype: HTMLTruhlarAmbulanceWeListElement;
        new (): HTMLTruhlarAmbulanceWeListElement;
    };
    interface HTMLElementTagNameMap {
        "truhlar-ambulance-we-list": HTMLTruhlarAmbulanceWeListElement;
    }
}
declare namespace LocalJSX {
    interface TruhlarAmbulanceWeList {
    }
    interface IntrinsicElements {
        "truhlar-ambulance-we-list": TruhlarAmbulanceWeList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "truhlar-ambulance-we-list": LocalJSX.IntrinsicElements["truhlar-ambulance-we-list"] & JSXBase.HTMLAttributes<HTMLTruhlarAmbulanceWeListElement>;
        }
    }
}
