/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XdtAmbulanceWlApp {
        "ambulanceId": string;
        "apiBase": string;
        /**
          * @default ""
         */
        "basePath": string;
    }
    interface XdtAmbulanceWlEditor {
        "entryId": string;
    }
    interface XdtAmbulanceWlList {
        "ambulanceId": string;
        "apiBase": string;
    }
}
export interface XdtAmbulanceWlEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXdtAmbulanceWlEditorElement;
}
export interface XdtAmbulanceWlListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLXdtAmbulanceWlListElement;
}
declare global {
    interface HTMLXdtAmbulanceWlAppElement extends Components.XdtAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLXdtAmbulanceWlAppElement: {
        prototype: HTMLXdtAmbulanceWlAppElement;
        new (): HTMLXdtAmbulanceWlAppElement;
    };
    interface HTMLXdtAmbulanceWlEditorElementEventMap {
        "editor-closed": string;
    }
    interface HTMLXdtAmbulanceWlEditorElement extends Components.XdtAmbulanceWlEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXdtAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLXdtAmbulanceWlEditorElement, ev: XdtAmbulanceWlEditorCustomEvent<HTMLXdtAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXdtAmbulanceWlEditorElementEventMap>(type: K, listener: (this: HTMLXdtAmbulanceWlEditorElement, ev: XdtAmbulanceWlEditorCustomEvent<HTMLXdtAmbulanceWlEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXdtAmbulanceWlEditorElement: {
        prototype: HTMLXdtAmbulanceWlEditorElement;
        new (): HTMLXdtAmbulanceWlEditorElement;
    };
    interface HTMLXdtAmbulanceWlListElementEventMap {
        "entry-clicked": string;
    }
    interface HTMLXdtAmbulanceWlListElement extends Components.XdtAmbulanceWlList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLXdtAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLXdtAmbulanceWlListElement, ev: XdtAmbulanceWlListCustomEvent<HTMLXdtAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLXdtAmbulanceWlListElementEventMap>(type: K, listener: (this: HTMLXdtAmbulanceWlListElement, ev: XdtAmbulanceWlListCustomEvent<HTMLXdtAmbulanceWlListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLXdtAmbulanceWlListElement: {
        prototype: HTMLXdtAmbulanceWlListElement;
        new (): HTMLXdtAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xdt-ambulance-wl-app": HTMLXdtAmbulanceWlAppElement;
        "xdt-ambulance-wl-editor": HTMLXdtAmbulanceWlEditorElement;
        "xdt-ambulance-wl-list": HTMLXdtAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XdtAmbulanceWlApp {
        "ambulanceId"?: string;
        "apiBase"?: string;
        /**
          * @default ""
         */
        "basePath"?: string;
    }
    interface XdtAmbulanceWlEditor {
        "entryId"?: string;
        "onEditor-closed"?: (event: XdtAmbulanceWlEditorCustomEvent<string>) => void;
    }
    interface XdtAmbulanceWlList {
        "ambulanceId"?: string;
        "apiBase"?: string;
        "onEntry-clicked"?: (event: XdtAmbulanceWlListCustomEvent<string>) => void;
    }

    interface XdtAmbulanceWlAppAttributes {
        "basePath": string;
        "apiBase": string;
        "ambulanceId": string;
    }
    interface XdtAmbulanceWlEditorAttributes {
        "entryId": string;
    }
    interface XdtAmbulanceWlListAttributes {
        "apiBase": string;
        "ambulanceId": string;
    }

    interface IntrinsicElements {
        "xdt-ambulance-wl-app": Omit<XdtAmbulanceWlApp, keyof XdtAmbulanceWlAppAttributes> & { [K in keyof XdtAmbulanceWlApp & keyof XdtAmbulanceWlAppAttributes]?: XdtAmbulanceWlApp[K] } & { [K in keyof XdtAmbulanceWlApp & keyof XdtAmbulanceWlAppAttributes as `attr:${K}`]?: XdtAmbulanceWlAppAttributes[K] } & { [K in keyof XdtAmbulanceWlApp & keyof XdtAmbulanceWlAppAttributes as `prop:${K}`]?: XdtAmbulanceWlApp[K] };
        "xdt-ambulance-wl-editor": Omit<XdtAmbulanceWlEditor, keyof XdtAmbulanceWlEditorAttributes> & { [K in keyof XdtAmbulanceWlEditor & keyof XdtAmbulanceWlEditorAttributes]?: XdtAmbulanceWlEditor[K] } & { [K in keyof XdtAmbulanceWlEditor & keyof XdtAmbulanceWlEditorAttributes as `attr:${K}`]?: XdtAmbulanceWlEditorAttributes[K] } & { [K in keyof XdtAmbulanceWlEditor & keyof XdtAmbulanceWlEditorAttributes as `prop:${K}`]?: XdtAmbulanceWlEditor[K] };
        "xdt-ambulance-wl-list": Omit<XdtAmbulanceWlList, keyof XdtAmbulanceWlListAttributes> & { [K in keyof XdtAmbulanceWlList & keyof XdtAmbulanceWlListAttributes]?: XdtAmbulanceWlList[K] } & { [K in keyof XdtAmbulanceWlList & keyof XdtAmbulanceWlListAttributes as `attr:${K}`]?: XdtAmbulanceWlListAttributes[K] } & { [K in keyof XdtAmbulanceWlList & keyof XdtAmbulanceWlListAttributes as `prop:${K}`]?: XdtAmbulanceWlList[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xdt-ambulance-wl-app": LocalJSX.IntrinsicElements["xdt-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLXdtAmbulanceWlAppElement>;
            "xdt-ambulance-wl-editor": LocalJSX.IntrinsicElements["xdt-ambulance-wl-editor"] & JSXBase.HTMLAttributes<HTMLXdtAmbulanceWlEditorElement>;
            "xdt-ambulance-wl-list": LocalJSX.IntrinsicElements["xdt-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLXdtAmbulanceWlListElement>;
        }
    }
}
